# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nateh\PycharmProjects\pyChat\pyChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 825)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 181, 191))
        self.groupBox.setObjectName("groupBox")
        self.serverIP_label = QtWidgets.QLabel(self.groupBox)
        self.serverIP_label.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.serverIP_label.setObjectName("serverIP_label")
        self.port_label = QtWidgets.QLabel(self.groupBox)
        self.port_label.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.port_label.setObjectName("port_label")
        self.establishServer_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.establishServer_pushButton.setGeometry(QtCore.QRect(10, 110, 91, 23))
        self.establishServer_pushButton.setObjectName("establishServer_pushButton")
        self.shutdownServer_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.shutdownServer_pushButton.setGeometry(QtCore.QRect(10, 150, 91, 23))
        self.shutdownServer_pushButton.setObjectName("shutdownServer_pushButton")
        self.serverIP_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.serverIP_lineEdit.setGeometry(QtCore.QRect(60, 30, 113, 20))
        self.serverIP_lineEdit.setObjectName("serverIP_lineEdit")
        self.port_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.port_lineEdit.setGeometry(QtCore.QRect(60, 60, 113, 20))
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.serverActivityLog_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.serverActivityLog_textEdit.setGeometry(QtCore.QRect(10, 240, 441, 511))
        self.serverActivityLog_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.serverActivityLog_textEdit.setObjectName("serverActivityLog_textEdit")
        self.serverActivityLog_label = QtWidgets.QLabel(self.centralwidget)
        self.serverActivityLog_label.setGeometry(QtCore.QRect(10, 215, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.serverActivityLog_label.setFont(font)
        self.serverActivityLog_label.setLineWidth(1)
        self.serverActivityLog_label.setIndent(-4)
        self.serverActivityLog_label.setObjectName("serverActivityLog_label")
        self.clearLog_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearLog_pushButton.setGeometry(QtCore.QRect(190, 760, 75, 23))
        self.clearLog_pushButton.setObjectName("clearLog_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyChat Server"))
        self.groupBox.setTitle(_translate("MainWindow", "Host"))
        self.serverIP_label.setText(_translate("MainWindow", "ServerIP"))
        self.port_label.setText(_translate("MainWindow", "Port"))
        self.establishServer_pushButton.setText(_translate("MainWindow", "Establish Server"))
        self.shutdownServer_pushButton.setText(_translate("MainWindow", "Shutdown Server"))
        self.serverActivityLog_label.setText(_translate("MainWindow", "Server Activity"))
        self.clearLog_pushButton.setText(_translate("MainWindow", "Clear"))
